### ISSUE TITLE
[Wish] Clone a node

### ISSUE THREAD

**Issue by no-e-in** [x28de/mytool#6]
I have an X node with 14 connections. I make a copy of X and divide the links (7 with X and 7 with the copy of X). Then I correct the detail of X but its copy keeps the old detail. Is it possible to clone a node so that its clones change when the original changes? 

P.S. I hope that with github there are no more email problems.

**Comment by x28de** [comment]
Unfortunately, what you want would be completely beyond the data model. Instead of copying, I would perhaps create two auxiliary nodes (they may be even without a label and detail), with additional connections to the original X node where the details live. These connections may even be pale if they otherwise disturb the gestalt pattern or oversight.

**Comment by no-e-in** [comment]
Thank you for the answer.
